name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  wake-app:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

          cat << 'EOF' > wake.py
          from playwright.sync_api import sync_playwright
          import time

          with sync_playwright() as p:
              browser = p.chromium.launch(headless=True)
              try:
                  page = browser.new_page()
                  print('Visiting app...')
                  page.goto('https://ai-caption-generator.streamlit.app/', wait_until='load')
                  time.sleep(15)
                  print('Page loaded and waited.')
              finally:
                  browser.close()
          print("✅ Script completed successfully — Streamlit app pinged.")
          EOF

          python wake.py
